//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicinaRegenerativa.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A06236_turnosMedicEntities : DbContext
    {
        public DB_A06236_turnosMedicEntities()
            : base("name=DB_A06236_turnosMedicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Calendario> Calendario { get; set; }
        public virtual DbSet<HistorialPacientes> HistorialPacientes { get; set; }
        public virtual DbSet<Pacientes> Pacientes { get; set; }
        public virtual DbSet<TipoTurnos> TipoTurnos { get; set; }
        public virtual DbSet<Turnos> Turnos { get; set; }
        public virtual DbSet<ObrasSociales> ObrasSociales { get; set; }
    }
}
