//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicinaRegenerativa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresupuestosIngresos
    {
        public int idPresupuestoIngreso { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<byte> Cuota { get; set; }
        public string Observaciones { get; set; }
        public int idPresupuestos { get; set; }
        public byte idTipoMoneda { get; set; }
        public Nullable<byte> idMedioPago { get; set; }
        public string FacturaNro { get; set; }
        public Nullable<System.DateTime> FechaCarga { get; set; }
        public string UserId { get; set; }
    
        public virtual MediosPago MediosPago { get; set; }
        public virtual Presupuestos Presupuestos { get; set; }
        public virtual TiposMoneda TiposMoneda { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
