//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicinaRegenerativa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Presupuestos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Presupuestos()
        {
            this.PresupuestosIngresos = new HashSet<PresupuestosIngresos>();
        }
    
        public int idPresupuestos { get; set; }
        [DataType(DataType.Currency)]
        //[DisplayFormat(DataFormatString = "{0:c}")]
        
        public Nullable<decimal> Precio { get; set; }
        public Nullable<byte> Cuotas { get; set; }
        public string Observaciones { get; set; }
        public int idPaciente { get; set; }
        public int idTipoTurno { get; set; }
        public byte idEstadoPresupuesto { get; set; }
        [Display(Name = "Fecha de Carga")]
        public Nullable<System.DateTime> FechaCarga { get; set; }
        public string UserId { get; set; }
    
        public virtual EstadosPresupuestos EstadosPresupuestos { get; set; }
        public virtual Pacientes Pacientes { get; set; }
        public virtual TipoTurnos TipoTurnos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PresupuestosIngresos> PresupuestosIngresos { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
